version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    user: "root:root"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
